### ISSUE TITLE
formula formatting

### ISSUE THREAD

**Issue by maryglover** [SESYNC-ci/model-lang-lesson#8]
Formulas in lme4.Rmd are not displayed properly

**Comment by qdread** [comment]
I think the lesson just hadn't been built in a long time, so the fixes to Latex formatting hadn't gone through. To get it to build, I had to fix a few things, such as changing everywhere it said `data=person` to `data=pums`. Then it built and I pushed it with commit 9ee02eb. You can see that now the three formulas each are on their own line on the lesson page.
